### ISSUE TITLE
Request parameter is not available at one place

### ISSUE THREAD

**Issue by mdsadiq** [gedennis/koa2-validation#1]
Right now, to access

- body, data is available in,  **ctx.request.body**
- params, data is available in, **ctx.params**
- query, data is available in, **ctx.request.query**

Can we get consistency in accessing request parameters ?

**Comment by gedennis** [comment]
Yeah, it will be better to keep consistency to access the params。But it is about @koa 。Koa gets the request（header, query,params） with ctx, except the ```body```。And use the koa-bodyparser to add the body in request。
